### ISSUE TITLE
Add comments to code

### ISSUE THREAD

**Issue by krsna6** [usc-sail/mica-text-script-parser#3]
None of the code is commented. I am trying to run this parser on a standalone pdf  - and there are no instructions on where to begin with. Can you please add comments and give a few use cases, such as fetching from a webpage, or running on a pdf, etc.

**Comment by sabyasachee** [comment]
The parser does not work on input where the indentations are not preserved.
Thus it does not work on pdfs for which we haven't yet found a good solution to extract the text while preserving indentation.

We can change the parser to work without the indent information.

**Comment by sabyasachee** [comment]
Development has shifted to noindent parser file.
